version: '2'

services:
  stork:
    container_name: "stork"
    build: 
        context: "."
        dockerfile: "Dockerfile"
    volumes:
      - .:/code
      - .db_data/db.sqlite3:/db.sqlite3
    ports:
      - "8000:8000"
    #restart: "unless-stopped"
