version: 2
jobs:
  lint_css:
    docker:
      - image: circleci/node:stretch
    branches:
      ignore:
        - master
    steps:
      - checkout
      - npm install stylelint -g
      - stylelint storkbaby/storkbabyapp/static/stork.css
  build:
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
    branches:
      ignore:
        - master
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            sudo pip install flake8
            sudo pip install -r requirements.txt
      - run:
          command: |
            flake8 storkbaby/storkbabyapp/*.py
