# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-12-05 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='profilepics')),
                ('description', models.CharField(max_length=250)),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
    ]
