# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-09-17 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferenceID', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('preferenceID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_preferenceID', to='storkbabyapp.preference')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=0)),
                ('userType', models.IntegerField(default=0)),
                ('emailAddress', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='userPreferenceMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferenceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpreferencemapping_preferenceID', to='storkbabyapp.preference')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpreferencemapping_userID', to='storkbabyapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='userRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatingUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrelation_relatingUser', to='storkbabyapp.user')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrelation_userID', to='storkbabyapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_reviewer', to='storkbabyapp.user'),
        ),
        migrations.AddField(
            model_name='review',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_users', to='storkbabyapp.user'),
        ),
    ]
