# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-09-18 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storkbabyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userChildMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userchildmapping_userID', to='storkbabyapp.users')),
            ],
        ),
    ]
