# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-09-18 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storkbabyapp', '0002_userchildmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_userID', to='storkbabyapp.users'),
        ),
    ]
