# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-09-18 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storkbabyapp', '0003_auto_20190918_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='user',
            new_name='userID',
        ),
    ]
