# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-09-18 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storkbabyapp', '0005_userexperiencemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexperiencemapping',
            name='experience',
            field=models.CharField(max_length=200),
        ),
    ]
