# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-09-18 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storkbaby', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='preferenceID',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpreferencemapping',
            name='preferenceID',
        ),
        migrations.RemoveField(
            model_name='userpreferencemapping',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='userrelations',
            name='relatingUser',
        ),
        migrations.RemoveField(
            model_name='userrelations',
            name='userID',
        ),
        migrations.DeleteModel(
            name='preferences',
        ),
        migrations.DeleteModel(
            name='reviews',
        ),
        migrations.DeleteModel(
            name='userPreferenceMapping',
        ),
        migrations.DeleteModel(
            name='userRelations',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
